/**
 * Pre-hydrated Architecture Topology Scenarios.
 *
 * For seamless live demonstration and Interactive Topology Exploration.
 * When responders or judges view the graph, pre-hydrated scenarios provide
 * rich, realistic microservice dependency architectures immediately, while
 * still fully supporting dynamic expansion from live speech.
 */

import type { Scenario } from "./types";

export const TOPOLOGY_SCENARIOS: Scenario[] = [
  {
    id: "clean",
    name: "Live Speech (Default)",
    description: "Blank canvas that synthesizes topology dynamically as speakers talk on the bridge.",
    badge: "LIVE",
    entities: [],
    links: [],
  },
  {
    id: "ecommerce_checkout",
    name: "E-Commerce Checkout Degradation",
    description: "Ingress proxy reporting 5xx spikes cascading through Checkout down to third-party payment gateway.",
    badge: "SEV-1 P0",
    entities: [
      {
        id: "ingress",
        label: "Ingress Gateway",
        kind: "gateway",
        status: "CRITICAL",
        detail: "Envoy Edge Proxy",
        metric: "12.4% 5xx",
        aliases: ["edge", "proxy", "gateway"],
      },
      {
        id: "auth",
        label: "Auth Service",
        kind: "service",
        status: "OK",
        detail: "JWT Verification",
        metric: "42ms p99",
        aliases: ["authentication", "auth-service"],
      },
      {
        id: "checkout",
        label: "Checkout Service",
        kind: "service",
        status: "CRITICAL",
        detail: "Payment Processing",
        metric: "2,840ms p99",
        aliases: ["cart", "checkout-service", "order-api"],
      },
      {
        id: "redis",
        label: "Redis Primary",
        kind: "datastore",
        status: "OK",
        detail: "Session Cache (us-east-1a)",
        metric: "34.2% mem",
        aliases: ["cache", "redis-cluster", "redis-primary"],
      },
      {
        id: "postgres",
        label: "Postgres Primary",
        kind: "datastore",
        status: "OK",
        detail: "Orders Relational DB",
        metric: "48% pool",
        aliases: ["db", "database", "postgres-db"],
      },
      {
        id: "stripe",
        label: "Stripe Connector",
        kind: "gateway",
        status: "CRITICAL",
        detail: "Outbound Payment API",
        metric: "38.5% timeout",
        aliases: ["stripe-gateway", "payment-processor"],
      },
      {
        id: "network",
        label: "VPC Netpath (us-east-1a)",
        kind: "network",
        status: "CRITICAL",
        detail: "AWS Transit Gateway",
        metric: "92.4% loss",
        aliases: ["netpath", "vpc", "network-transit"],
      },
    ],
    links: [
      { id: "l1", source: "ingress", target: "auth", label: "authenticates", kind: "depends" },
      { id: "l2", source: "ingress", target: "checkout", label: "routes /pay", kind: "depends" },
      { id: "l3", source: "checkout", target: "redis", label: "session lookup", kind: "depends" },
      { id: "l4", source: "checkout", target: "postgres", label: "orders write", kind: "depends" },
      { id: "l5", source: "checkout", target: "stripe", label: "charge request", kind: "depends" },
      { id: "l6", source: "checkout", target: "network", label: "transit latency", kind: "suspected" },
      { id: "l7", source: "stripe", target: "network", label: "dropped SYN packets", kind: "causal" },
    ],
    initialClaims: [
      {
        id: "sc-hyp-redis",
        text: "Maybe Redis is out of memory and evicting session keys",
        entity: "redis",
        epistemicStatus: "HYPOTHESIS",
        speakerRole: "DevOps Lead",
        confidence: 0.75,
        at: Date.now() - 120000,
        lifecycle: "ACTIVE",
      },
      {
        id: "sc-hyp-db-pool",
        text: "Could the Postgres primary connection pool be exhausted?",
        entity: "postgres",
        epistemicStatus: "HYPOTHESIS",
        speakerRole: "Database Admin",
        confidence: 0.7,
        at: Date.now() - 95000,
        lifecycle: "ACTIVE",
      },
      {
        id: "sc-hyp-net-drop",
        text: "Is the VPC transit gateway dropping packets to us-east-1a?",
        entity: "network",
        epistemicStatus: "HYPOTHESIS",
        speakerRole: "Site Reliability Engineer",
        confidence: 0.85,
        at: Date.now() - 60000,
        lifecycle: "ACTIVE",
      },
      {
        id: "sc-tool-net-drop",
        text: "CloudWatch telemetry: VPC Netpath us-east-1a packet drop rate is 92.4% (baseline: <0.1%, RTT: 340ms).",
        entity: "network",
        epistemicStatus: "TOOL_RESULT",
        speakerRole: "CloudWatch",
        confidence: 1.0,
        at: Date.now() - 30000,
        lifecycle: "ACTIVE",
      },
    ],
  },
  {
    id: "database_failover",
    name: "Database Replication Lag & Deadlocks",
    description: "Postgres replica falling 480s behind primary, threatening failover data loss and connection pool starvation.",
    badge: "SEV-2 P1",
    entities: [
      {
        id: "web-app",
        label: "Web App Fleet",
        kind: "service",
        status: "WARNING",
        detail: "Next.js Frontend Fleet",
        metric: "850ms p99",
        aliases: ["frontend", "web"],
      },
      {
        id: "order-service",
        label: "Order Service",
        kind: "service",
        status: "WARNING",
        detail: "Order Management API",
        metric: "Pool Wait 4.2s",
        aliases: ["orders", "api"],
      },
      {
        id: "postgres",
        label: "Postgres Primary",
        kind: "datastore",
        status: "OK",
        detail: "Write Primary (us-east-1a)",
        metric: "52% pool",
        aliases: ["db-primary", "postgres-main"],
      },
      {
        id: "postgres-replica",
        label: "Postgres Replica",
        kind: "datastore",
        status: "CRITICAL",
        detail: "Read Replica (us-east-1b)",
        metric: "482s lag",
        aliases: ["read-replica", "replica-db"],
      },
      {
        id: "wal-archiver",
        label: "WAL Archiver",
        kind: "service",
        status: "CRITICAL",
        detail: "WAL Stream Shipping",
        metric: "1,420 backlog",
        aliases: ["archiver", "wal-stream"],
      },
      {
        id: "s3-backup",
        label: "S3 WAL Archive",
        kind: "datastore",
        status: "OK",
        detail: "AWS S3 Bucket",
        metric: "Active",
        aliases: ["s3", "cold-storage"],
      },
    ],
    links: [
      { id: "dl1", source: "web-app", target: "order-service", label: "submits order", kind: "depends" },
      { id: "dl2", source: "order-service", target: "postgres", label: "tx write", kind: "depends" },
      { id: "dl3", source: "order-service", target: "postgres-replica", label: "read query", kind: "depends" },
      { id: "dl4", source: "postgres", target: "wal-archiver", label: "wal generation", kind: "causal" },
      { id: "dl5", source: "wal-archiver", target: "postgres-replica", label: "replay queue", kind: "causal" },
      { id: "dl6", source: "wal-archiver", target: "s3-backup", label: "sync upload", kind: "depends" },
    ],
  },
  {
    id: "network_partition",
    name: "VPC Network Partition (Golden Demo)",
    description: "AZ us-east-1a partition triggering intermittent cache timeouts while Redis primary remains completely healthy.",
    badge: "SEV-1 P0",
    entities: [
      {
        id: "ingress",
        label: "Ingress Gateway",
        kind: "gateway",
        status: "WARNING",
        detail: "Global Load Balancer",
        metric: "2,100ms p99",
        aliases: ["alb", "edge"],
      },
      {
        id: "checkout",
        label: "Checkout Service",
        kind: "service",
        status: "CRITICAL",
        detail: "Running in us-east-1a",
        metric: "3,100ms p99",
        aliases: ["checkout-api"],
      },
      {
        id: "inventory",
        label: "Inventory Service",
        kind: "service",
        status: "OK",
        detail: "Running in us-east-1b",
        metric: "45ms p99",
        aliases: ["inventory-api"],
      },
      {
        id: "redis",
        label: "Redis Primary",
        kind: "datastore",
        status: "OK",
        detail: "Running in us-east-1b",
        metric: "34.2% mem",
        aliases: ["redis-cache"],
      },
      {
        id: "network",
        label: "VPC Netpath (us-east-1a)",
        kind: "network",
        status: "CRITICAL",
        detail: "AWS Transit Gateway Interface",
        metric: "92.4% loss",
        aliases: ["transit-gateway", "eni-08d41a7b"],
      },
    ],
    links: [
      { id: "nl1", source: "ingress", target: "checkout", label: "routes traffic", kind: "depends" },
      { id: "nl2", source: "ingress", target: "inventory", label: "stock lookup", kind: "depends" },
      { id: "nl3", source: "checkout", target: "redis", label: "timeouts", kind: "suspected" },
      { id: "nl4", source: "checkout", target: "network", label: "inter-AZ packet loss", kind: "causal" },
      { id: "nl5", source: "network", target: "redis", label: "partitioned transit", kind: "causal" },
    ],
  },
];

